# Generated by Django 5.2.7 on 2025-10-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
            ],
        ),
    ]
